name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # 1. Configura o Java 17 de forma nativa no GitHub
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2. Instala os pacotes do sistema
      - name: Instalar pacotes do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      # 3. Instala o Buildozer e o Cython globalmente no Python da máquina
      - name: Instalar Buildozer
        run: |
          pip3 install --user --upgrade Cython==0.29.33 virtualenv buildozer

      # 4. Aceita todas as licenças do Android automaticamente (Resolve o erro do "yes")
      - name: Aceitar Licenças do Android
        run: |
          yes | buildozer android debug || true

      # 5. Roda o comando final para gerar o pacote
      - name: Compilar o APK
        run: buildozer android debug

      - name: Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: h2opro-apk
          path: bin/*.apk
