name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # Fixamos a versão do sistema para evitar pacotes quebrados

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar dependências do sistema
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Compilar com Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: latest

      - name: Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: h2opro-apk
          path: bin/*.apk
